In [ ]:
import numpy as np
help(np)

In [11]:
a = np.array([1,23,5,8])

In [3]:
a[1]

23

In [4]:
len(a)

4

In [7]:
for i in a:
  print(i, end = ' ')

1 23 5 8 

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int64')

In [18]:
a = np.array([1,23,5,8])
a.dtype

dtype('int64')

In [19]:
a[0] = 10.6
a

array([10, 23,  5,  8])

In [22]:
int('12')

12

In [25]:
a[2] = 12.6   # dar tabdil float be int , mamoolan be samte paeen gerd mishavad.
a

array([10, 23, 12,  8])

In [26]:
b = np.array([12.3,10,20,30])
b

array([12.3, 10. , 20. , 30. ])

In [28]:
b = np.array([12,10.1,20.3,30.8])  # agar araye tarkibi az int , float bashad, ham ro tabdil be float mikonad.
b

array([12. , 10.1, 20.3, 30.8])

In [30]:
b= np.array([12.3,10,20,30], dtype = str)
b

array(['12.3', '10', '20', '30'], dtype='<U4')

In [ ]:
b= np.array([12.3,10,20,30], dtype = str)

In [39]:
c = b.astype(float)  # baraye tabdile araye be float
c

array([12.3, 10. , 20. , 30. ])

In [44]:
print(b.size )  # kole tedade elementhaye yek matrix
print(b)

4
[12.3 10.  20.  30. ]


In [45]:
b.shape # abaade yek matix be soorate tople

(4,)

In [46]:
b.ndim  # tedade abaade

1

In [20]:
c = np.array([[1,4,8,9,5],[5,3,9,2,6]])
c

array([[1, 4, 8, 9, 5],
       [5, 3, 9, 2, 6]])

In [7]:
c.shape

(2, 4)

In [8]:
c.ndim

2

In [9]:
c.astype(float)

array([[1., 4., 8., 9.],
       [5., 3., 9., 2.]])

In [10]:
c

array([[1, 4, 8, 9],
       [5, 3, 9, 2]])

In [11]:
c.size

8

In [12]:
c[0]

array([1, 4, 8, 9])

In [13]:
len(c)

2

In [15]:
c[1,2]  # be 2 shekl mitavan be anasore yek matrix dastresi dasht.

9

In [16]:
c[1][2]

9

In [21]:
c[:,2]

array([8, 9])

In [26]:
q = c[:,1:4:2]
q

array([[4, 9],
       [3, 2]])

In [29]:
q[0,0] = 1000
print(q)


[[1000    9]
 [   3    2]]


In [30]:
c

array([[   1, 1000,    8,    9,    5],
       [   5,    3,    9,    2,    6]])